-- Englisify Supabase schema (latest)
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- Global cards are public. User-created cards are private to their owner.

-- 1. Per-user application data: progress, settings, favorites, etc.
create table if not exists public.user_data (
  user_id uuid not null references auth.users(id) on delete cascade,
  data_key text not null,
  data_value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, data_key)
);

alter table public.user_data enable row level security;
drop policy if exists "Users can read their own data" on public.user_data;
drop policy if exists "Users can insert their own data" on public.user_data;
drop policy if exists "Users can update their own data" on public.user_data;
drop policy if exists "Users can delete their own data" on public.user_data;

create policy "Users can read their own data" on public.user_data
  for select using (auth.uid() = user_id);
create policy "Users can insert their own data" on public.user_data
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own data" on public.user_data
  for update using (auth.uid() = user_id);
create policy "Users can delete their own data" on public.user_data
  for delete using (auth.uid() = user_id);

create or replace function public.set_user_data_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_data_updated_at on public.user_data;
create trigger user_data_updated_at
before update on public.user_data
for each row execute function public.set_user_data_updated_at();

-- 2. Global flashcards. The website reads this exact table.
-- Existing rows are preserved; this only creates the table if missing.
create table if not exists public.flashcard (
  id bigint generated by default as identity primary key,
  level text not null default 'A1',
  word text not null,
  ipa text not null default '',
  type text not null default 'noun',
  meaning text not null,
  example text not null default ''
);

alter table public.flashcard enable row level security;
drop policy if exists "Anyone can read flashcards" on public.flashcard;
create policy "Anyone can read flashcards" on public.flashcard
  for select using (true);

-- 3. User-created flashcards. Existing bigint user_id is retained for compatibility.
-- auth_user_id is the Supabase Auth UUID used for ownership and RLS.
alter table if exists public.user_flashcards
  add column if not exists auth_user_id uuid references auth.users(id) on delete cascade;

alter table if exists public.user_flashcards enable row level security;
drop policy if exists "Users can read their own flashcards" on public.user_flashcards;
drop policy if exists "Users can insert their own flashcards" on public.user_flashcards;
drop policy if exists "Users can update their own flashcards" on public.user_flashcards;
drop policy if exists "Users can delete their own flashcards" on public.user_flashcards;

create policy "Users can read their own flashcards" on public.user_flashcards
  for select using (auth.uid() = auth_user_id);
create policy "Users can insert their own flashcards" on public.user_flashcards
  for insert with check (auth.uid() = auth_user_id);
create policy "Users can update their own flashcards" on public.user_flashcards
  for update using (auth.uid() = auth_user_id);
create policy "Users can delete their own flashcards" on public.user_flashcards
  for delete using (auth.uid() = auth_user_id);

