-- Englisify Supabase schema (latest)
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- Global cards are public. User-created cards are private to their owner.

-- 1. Per-user application data: progress, settings, favorites, etc.
create table if not exists public.user_data (
  user_id uuid not null references auth.users(id) on delete cascade,
  data_key text not null,
  data_value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, data_key)
);

alter table public.user_data enable row level security;
drop policy if exists "Users can read their own data" on public.user_data;
drop policy if exists "Users can insert their own data" on public.user_data;
drop policy if exists "Users can update their own data" on public.user_data;
drop policy if exists "Users can delete their own data" on public.user_data;

create policy "Users can read their own data" on public.user_data
  for select using (auth.uid() = user_id);
create policy "Users can insert their own data" on public.user_data
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own data" on public.user_data
  for update using (auth.uid() = user_id);
create policy "Users can delete their own data" on public.user_data
  for delete using (auth.uid() = user_id);

create or replace function public.set_user_data_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_data_updated_at on public.user_data;
create trigger user_data_updated_at
before update on public.user_data
for each row execute function public.set_user_data_updated_at();

-- 2. Global flashcards. The website reads this exact table.
-- Existing rows are preserved; this only creates the table if missing.
create table if not exists public.flashcard (
  id bigint generated by default as identity primary key,
  level text not null default 'A1',
  word text not null,
  ipa text not null default '',
  type text not null default 'noun',
  meaning text not null,
  example text not null default ''
);

alter table public.flashcard enable row level security;
drop policy if exists "Anyone can read flashcards" on public.flashcard;
drop policy if exists "Authenticated users can insert flashcards" on public.flashcard;

create policy "Anyone can read flashcards" on public.flashcard
  for select using (true);

create policy "Authenticated users can insert flashcards" on public.flashcard
  for insert with check (auth.uid() is not null);

-- 3. User vocabulary learning history
-- Tracks when users study flashcards and calculates next review dates
create table if not exists public.user_vocabulary_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  last_studied timestamptz not null default now(),
  next_review timestamptz not null default (now() + interval '1 day'),
  review_count int not null default 1,
  rating text not null default 'good',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, word)
);

alter table public.user_vocabulary_history enable row level security;
drop policy if exists "Users can read their own vocabulary history" on public.user_vocabulary_history;
drop policy if exists "Users can insert their own vocabulary history" on public.user_vocabulary_history;
drop policy if exists "Users can update their own vocabulary history" on public.user_vocabulary_history;
drop policy if exists "Users can delete their own vocabulary history" on public.user_vocabulary_history;

create policy "Users can read their own vocabulary history" on public.user_vocabulary_history
  for select using (auth.uid() = user_id);
create policy "Users can insert their own vocabulary history" on public.user_vocabulary_history
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own vocabulary history" on public.user_vocabulary_history
  for update using (auth.uid() = user_id);
create policy "Users can delete their own vocabulary history" on public.user_vocabulary_history
  for delete using (auth.uid() = user_id);

create or replace function public.set_vocabulary_history_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists vocabulary_history_updated_at on public.user_vocabulary_history;
create trigger vocabulary_history_updated_at
before update on public.user_vocabulary_history
for each row execute function public.set_vocabulary_history_updated_at();

